# Generated by Django 2.2.6 on 2019-10-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('neighborhood', models.CharField(choices=[('Southwest', (('arnoldcreek', 'Arnold Creek'), ('ashcreek', 'Ashcreek'), ('bridlemile', 'Bridlemile'), ('collinsview', 'Collins View'), ('farsouthwest', 'Far Southwest'), ('hayhurst', 'Hayhurst'), ('healyheights', 'Healy Heights'), ('hillsdale', 'Hillsdale'), ('homestead', 'Homestead'), ('maplewood', 'Maplewood'), ('markham', 'Markham'), ('marshallpark', 'Marshall Park'), ('multnomah', 'Multnomah'), ('southburlingame', 'South Burlingame'), ('southportland', 'South Portland'), ('swhills', 'Southwest Hills'), ('westportlandpark', 'West Portland Park'))), ('Northwest', (('arlingtonheights', 'Arlington Heights'), ('downtown', 'Downtown Portland'), ('forestpark', 'Forest Park'), ('goosehollow', 'Goose Hollow'), ('hillside', 'Hillside'), ('linnton', 'Linnton'), ('nobhill', 'Nob Hill'), ('nwheights', 'Northwest Heights'), ('oldtown', 'Old Town Chinatown'), ('pearl', 'Pearl District'), ('sylvan', 'Sylvan Highlands'))), ('North', (('arborlodge', 'Arbor Lodge'), ('bridgeton', 'Bridgeton'), ('cathedralpark', 'Cathedral Park'), ('eastcolumbia', 'East Columbia'), ('haydenisland', 'Hayden Island'), ('kenton', 'Kenton'), ('overlook', 'Overlook'), ('piedmont', 'Piedmont'), ('portsmouth', 'Portsmouth'), ('stjohns', 'St. Johns'), ('universitypark', 'University Park'))), ('Northeast', (('alameda', 'Alameda'), ('beaumont', 'Beaumont-Wilshire'), ('boise', 'Boise'), ('concordia', 'Concordia'), ('cully', 'Cully'), ('eliot', 'Eliot'), ('grantpark', 'Grant Park'), ('hollywood', 'Hollywood'), ('humboldt', 'Humboldt'), ('irvington', 'Irvington'), ('king', 'King'), ('lloyd', 'Lloyd'), ('madisonsouth', 'Madison South'), ('rosecitypark', 'Rose City Park'), ('roseway', 'Roseway'), ('sabin', 'Sabin'), ('sullivansgulch', "Sullivan's Gulch"), ('sumner', 'Sumner'), ('sunderland', 'Sunderland'), ('vernon', 'Vernon'), ('woodlawn', 'Woodlawn'))), ('Southeast', (('brentwood', 'Brentwood-Darlington'), ('brooklyn', 'Brooklyn'), ('buckman', 'Buckman'), ('creston', 'Creston-Kenilworth'), ('eastmoreland', 'Eastmoreland'), ('foster', 'Foster-Powell'), ('hosfordabernathy', 'Hosford Abernathy'), ('kerns', 'Kerns'), ('laurelhurst', 'Laurelhurst'), ('montavilla', 'Montavilla'), ('mountscott', 'Mount Scott-Arleta'), ('mttabor', 'Mt. Tabor'), ('northtabor', 'North Tabor'), ('reed', 'Reed'), ('richmond', 'Richmond'), ('sellwood', 'Sellwood-Moreland'), ('southtabor', 'South Tabor'), ('sunnyside', 'Sunnyside'), ('woodstock', 'Woodstock'))), ('East', (('centennial', 'Centennial'), ('glenfair', 'Glenfair'), ('hazelwood', 'Hazelwood'), ('lents', 'Lents'), ('millpark', 'Mill Park'), ('pleasantvalley', 'Pleasant Valley'), ('powellhurst', 'Powellhurst Gilbert')))], max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('cuisines', models.ManyToManyField(to='carts.Cuisine')),
            ],
        ),
    ]
