# Generated by Django 2.2.6 on 2019-10-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='yelp',
            field=models.URLField(blank=True),
        ),
    ]
